kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: bbddmysql
provisioner: k8s.io/minikube-hostpath
parameters:
  type: pd-ssd

---

apiVersion: v1
kind: Service
metadata:
  name: mysqlsvc
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stmysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysqlsvc
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: myqsl
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "secret" 
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: bbddmysql
      resources:
        requests:
          storage: 3Gi



