#ingress minikube - minikube addons enable ingress
# 192.168.49.2 mipagina.com >>>>>> /etc/hosts 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
          - name: git-clone
            image: alpine/git # Any image with git will do
            command:
            - git
            - clone
            - https://github.com/benjamingordocortes/mipagina.git
            - /repo
            securityContext:
              runAsUser: 1 # Any non-root user will do. Match to the workload.
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
            volumeMounts:
              - name: git-repo
                mountPath: /repo
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html/
            name: git-repo
      volumes:
        - name: git-repo
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: mipagina 
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000

--- 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  labels:
    name: ingress
spec:
  rules:
  - host: mipagina.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mipagina
            port: 
              number: 80
